collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7107926
  lightness: 0.8153457
  brandStrength: 0.3229342
  brandColors:
    - '#1E211E'
    - '#ACB3BE'
    - '#6F7680'
    - '#FFFFFF'
    - '#E8E2CE'
  rhythmicContrast: 0.272344
typography_spectrum: 0.02675084
layout_spectrum: 0.501147
name: Kauai2015
