layout_spectrum: 0.501147
typography_spectrum: 0.02675084
color:
  saturation: 0.6502563
  lightness: 0.6952558
  brandStrength: 0.2480454
  rhythmicContrast: 0.2601009
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Kauai2015
